-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 18:25:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema t2g1_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `t2g1_db` ;

-- -----------------------------------------------------
-- Schema t2g1_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `t2g1_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `t2g1_db` ;

-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_categories` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_destinations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_destinations` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_destinations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longitude` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_products` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longitude` VARCHAR(255) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `stars` INT NULL DEFAULT NULL,
  `destination_id` BIGINT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKonodovuw5ooh97hpfyhovscqm` (`destination_id` ASC) VISIBLE,
  INDEX `FKcthu194f0icof6cxprcukmotk` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FKcthu194f0icof6cxprcukmotk`
    FOREIGN KEY (`category_id`)
    REFERENCES `t2g1_db`.`tb_categories` (`id`),
  CONSTRAINT `FKeojl1og02rqqyn4v913ih970r`
    FOREIGN KEY (`category_id`)
    REFERENCES `t2g1_db`.`tb_categories` (`id`),
  CONSTRAINT `FKonodovuw5ooh97hpfyhovscqm`
    FOREIGN KEY (`destination_id`)
    REFERENCES `t2g1_db`.`tb_destinations` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 160
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_images` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_images` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs13v4gqnfa2y0b88uuyay9oe4` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKs13v4gqnfa2y0b88uuyay9oe4`
    FOREIGN KEY (`product_id`)
    REFERENCES `t2g1_db`.`tb_products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 290
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_policies` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_policies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description` (`description` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 247
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_products_policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_products_policies` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_products_policies` (
  `policy_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`policy_id`, `product_id`),
  INDEX `FK69r13k1k72skb3boti7nq5i6j` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK69r13k1k72skb3boti7nq5i6j`
    FOREIGN KEY (`product_id`)
    REFERENCES `t2g1_db`.`tb_products` (`id`),
  CONSTRAINT `FKshr88hl4qwadou71bi69nhjns`
    FOREIGN KEY (`policy_id`)
    REFERENCES `t2g1_db`.`tb_policies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_utilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_utilities` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_utilities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 380
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_products_utilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_products_utilities` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_products_utilities` (
  `product_id` BIGINT NOT NULL,
  `utility_id` BIGINT NOT NULL,
  PRIMARY KEY (`product_id`, `utility_id`),
  INDEX `FK27h0u05vp4hf8occ6yjbxg8o6` (`utility_id` ASC) VISIBLE,
  CONSTRAINT `FK27h0u05vp4hf8occ6yjbxg8o6`
    FOREIGN KEY (`utility_id`)
    REFERENCES `t2g1_db`.`tb_utilities` (`id`),
  CONSTRAINT `FKqp3um8w5bfjgptj25g36s5il6`
    FOREIGN KEY (`product_id`)
    REFERENCES `t2g1_db`.`tb_products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_roles` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_users` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_non_expired` BIT(1) NOT NULL,
  `account_non_locked` BIT(1) NOT NULL,
  `credentials_non_expired` BIT(1) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` BIT(1) NOT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2bwdk5w4y4ehty96tvk2w66ow` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK2bwdk5w4y4ehty96tvk2w66ow`
    FOREIGN KEY (`role_id`)
    REFERENCES `t2g1_db`.`tb_roles` (`id`),
  CONSTRAINT `FKciptwywlm1l830jsu1he31pf5`
    FOREIGN KEY (`role_id`)
    REFERENCES `t2g1_db`.`tb_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `t2g1_db`.`tb_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t2g1_db`.`tb_reservations` ;

CREATE TABLE IF NOT EXISTS `t2g1_db`.`tb_reservations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `checkin_date_time` DATETIME(6) NULL DEFAULT NULL,
  `checkout_date_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlntpuhlwjmb5xa1nf6s5sbbvm` (`product_id` ASC) VISIBLE,
  INDEX `FKq6s1mbyymj2gxexc1cqa4xyds` (`client_id` ASC) VISIBLE,
  CONSTRAINT `FKq3a8qmp8sltux6sc4lr6g3j1r`
    FOREIGN KEY (`product_id`)
    REFERENCES `t2g1_db`.`tb_products` (`id`),
  CONSTRAINT `FKq6s1mbyymj2gxexc1cqa4xyds`
    FOREIGN KEY (`client_id`)
    REFERENCES `t2g1_db`.`tb_users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
